### PR TITLE
More verbose README.md

### PR DESCRIPTION
**Pull request by nikkehtine**
This change makes README.md easier to read. I also added the information that would help installing Chromium to %APPDATA% which I think is a better suited directory.

### CODE REVIEW

**Comment by nikkehtine** [comment]
This should also fix the issue I ran into:

```powershell
python update.py --install
Traceback (most recent call last):
  File "E:\Documents\code\git\ungoogled-updater\update.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by NeverDecaf** [comment]
Looks good except I don't want to recommend installing programs to `%APPDATA%`, this directory should only be used for user data, as the name implies. If you really want chromium to be accessible only by the current user, I believe `%LOCALAPPDATA%\Programs` is the accepted standard install location. (This may be more difficult to convey in the readme, as you need to change the path to `Path(os.getenv('LOCALAPPDATA'),'Programs','Ungoogled Chromium')`)

If you are installing to %APPDATA% because you want to make chromium accessible from elsewhere on your network, note that ungoogled chromium places user data in %LOCALAPPDATA% so your settings/profile would not be preserved anyway.

The most correct install location is, of course, %PROGRAMFILES% but IIRC there are some access issues when using that directory.

**Comment by NeverDecaf** [comment]
I don't want to change the default path in update.py because older users will then end up with 2 separate chromium installs if they use the newer version, though I do agree the default should be changed. I'll add a few options to the script as comments.

**Comment by nikkehtine** [comment]
Oops, I accidentally included my changed script and didn't notice...

**Pull request merged**
